/**
 * Copyright 2017 IBM Corp. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

package com.ibm.watson.developer_cloud.util;

import java.io.ByteArrayInputStream;
import java.io.InputStream;

/**
 * Helper class used by java code generated by the SDK codegen tool.
 */
public class StringHelper {

    private StringHelper() {
    }

    /**
     * Returns an InputStream that can be used to read the bytes of the specified String.
     * @param s the String that will back the InputStream
     * @return an InputStream to read the specified String
     */
    public static InputStream toInputStream(String s) {
        // TODO - check to see if we need to be concerned with the encoding of the string!
        return new ByteArrayInputStream(s.getBytes());
    }

    /**
     * Creates a parameterized part name for a form part based on a template and a key name and value.
     * Example:
     *     template: "{classname}_positive_examples"
     *     keyName:  "classname"
     *     keyValue: "truck"
     *     result: "truck_positive_examples"
     *
     * @param template the part name template
     * @param keyName the name of the key within the template
     * @param keyValue the value of the key to use as a replacement
     * @return the part name formed from the template, key name and key value
     */
    public static String createFormPartName(String template, String keyName, String keyValue) {
        String toBeReplaced = "{" + keyName + "}";
        return template.replace(toBeReplaced, keyValue);
    }
}
