# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will download a prebuilt Java version, install dependencies and run integration tests

name: Run Integration Tests

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration_test:
    name: Build and Run Integration Tests on Java ${{ matrix.java-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version: ['8']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'

    - name: Execute Java integration tests
      # continue-on-error: true
      env:
        MVN_ARGS: '-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
        NATURAL_LANGUAGE_UNDERSTANDING_APIKEY: ${{ secrets.NLU_APIKEY }}
        NATURAL_LANGUAGE_UNDERSTANDING_URL: "https://api.us-south.natural-language-understanding.watson.cloud.ibm.com"
        SPEECH_TO_TEXT_APIKEY: ${{ secrets.STT_APIKEY }}
        SPEECH_TO_TEXT_URL: "https://api.us-south.speech-to-text.watson.cloud.ibm.com"
        SPEECH_TO_TEXT_CUSTOM_ID: ${{ secrets.STT_APIKEY_CUSTOM_ID }}
        SPEECH_TO_TEXT_ACOUSTIC_CUSTOM_ID: ${{ secrets.STT_APIKEY_ACOUSTIC_CUSTOM_ID }}
        TEXT_TO_SPEECH_APIKEY: ${{ secrets.TTS_APIKEY }}
        TEXT_TO_SPEECH_URL: "https://api.us-south.text-to-speech.watson.cloud.ibm.com"
        ASSISTANT_APIKEY: ${{ secrets.WA_APIKEY }}
        ASSISTANT_WORKSPACE_ID: ${{ secrets.WA_WORKSPACE_ID }}
        ASSISTANT_ASSISTANT_ID: ${{ secrets.WA_ASSISTANT_ID }}
        ASSISTANT_URL: "https://api.us-south.assistant.watson.cloud.ibm.com"
        DISCOVERY_V2_APIKEY: ${{ secrets.D2_APIKEY }}
        DISCOVERY_V2_PROJECT_ID: ${{ secrets.D2_PROJECT_ID }}
        DISCOVERY_V2_COLLECTION_ID: ${{ secrets.D2_COLLECTION_ID }}
        DISCOVERY_V2_URL: "https://api.us-south.discovery.watson.cloud.ibm.com"
      run: |
        mvn test -Dtest=v1/AssistantServiceIT -DfailIfNoTests=false -pl assistant,common $MVN_ARGS
        mvn test -Dtest=v2/AssistantServiceIT -DfailIfNoTests=false -pl assistant,common $MVN_ARGS
        mvn test -Dtest=v2/DiscoveryIT -DfailIfNoTests=false -pl discovery,common $MVN_ARGS
        mvn test -Dtest=NaturalLanguageUnderstandingIT -DfailIfNoTests=false -pl natural-language-understanding,common $MVN_ARGS
        mvn test -Dtest=SpeechToTextIT -DfailIfNoTests=false -pl speech-to-text,common $MVN_ARGS
        mvn test -Dtest=TextToSpeechIT -DfailIfNoTests=false -pl text-to-speech,common $MVN_ARGS
        mvn test -Dtest=CustomizationsIT -DfailIfNoTests=false -pl text-to-speech,common $MVN_ARGS

      # Do not notify on success.  We will leave the code here just in case we decide to switch gears
    - name: Notify slack on success
      if: false # success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        status: SUCCESS
        color: good

    - name: Notify slack on failure
      if: false # failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        status: FAILED
        color: danger
